version: "3"

services: 
    flask:
        build: ./flask
        container_name: dailymotion_flask
        restart: always
        environment: 
            - APP_NAME=DailyMotionTest 
        expose:
            - 8080
        volumes:
            - ./flask/socket:/app/socket

    nginx:
        build: ./nginx
        container_name: dailymotion_nginx
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./flask/socket:/app/socket
        depends_on:
            - flask
