version: "3"

services: 
    flask:
        build: ./flask
        container_name: flask
        restart: always
        environment: 
            - APP_NAME=DailyMotionTest 
        expose:
            - 8080

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "5000:5000"
            
    mongodb:
        image: mongo
        restart: always
        container_name: mongo
        ports: 
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: likelion
            MONGO_INITDB_ROOT_PASSWORD: wearethefuture
        volumes:
            - /data/db:/data/db